server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/h2/data/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate.SQL: info
